### PR TITLE
NAM-281 -- UI: Create indicator to give user feedback when teacher is uploading photo

### PR DESCRIPTION
**Pull request by alecnicolas**
## ALEC MESSED UP
NAM-259 and NAM-260 are now also on this branch as well

# Description - NAM-281
Adds loading icon as feedback when uploading a new image to croppa.
  
# Testing
Upload the largest image file you have to a student's image so you can see the loading icon in action.

# Description - NAM-259 & 260
Flash card, gallery card, and list view cards have all been tweaked to be nicer with responsiveness and look less ugly.

# Testing
Play with the responsiveness window and make sure these views all still look good in multiple views.

### CODE REVIEW

**Review by liadGolan — CHANGES_REQUESTED** [review]
The Loading icon is not centered (it is left oriented)

**Review by liadGolan — CHANGES_REQUESTED** [review]
Loading icon still off center

Every thing is ok

**Review by liadGolan — APPROVED** [review]
It work now

**Review by andrewMETALAB — APPROVED** [review]
Good work!

**Pull request merged**
