### PR TITLE
NAM-534 -- ENG: Faculty images are not working

### PR DESCRIPTION
**Pull request by liadGolan**
# Description
fix media image urls and removes hard-coded url on front end
  
# Testing
1). log in as steve or Matt
2). see his profile image

### CODE REVIEW

**Review by luisjg — COMMENTED** [review]
See comments

**Review by jazperez — APPROVED** [review]
Si! Muy bien! 👍🏼

**Review by BrianLinggadjaja — APPROVED** [review]
Looks good, waiting for mentor approval!

**Review by luisjg — CHANGES_REQUESTED** [review]
See comments

**Review by luisjg — APPROVED** [review]
👍

**Pull request merged**
