### PR TITLE
NAM-489 -- UI: Fix styling of upload Modal

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Added CSS styling for upload modal.
  
# Testing
1. Visit student page and click the edit button.
2. Ensure the modal meets the requirements and doesn't break at different resolutions.

### CODE REVIEW

**Review by jazperez — APPROVED** [review]
It looks great, but just make sure to go back and delete console logs and alerts.

**Review by Tiffufu — DISMISSED** [review]
In addition to Jazmin's comment, could you please make the modal height slightly shorter and/or keep it from overlapping the bottom menu bar? I feel like the super modal removes a sense of being able to orient oneself in the app. (aka being within the Students tab)

**Review by chippingcolt — DISMISSED** [review]
yo man, maybe you noticed but just in case you didn't there are some files that touch backend and other parts of the app if you meant for those to be apart of this task slack me and I'll dismiss my review

**Review by liadGolan — DISMISSED** [review]
Uploading does not work for some reason. It works on dev

**Review by liadGolan — DISMISSED** [review]
On student uploaded photos, could you keep the modal the same size by leaving whitespace where the upload functionality is?

**Review by liadGolan — APPROVED** [review]
:+1:

**Pull request merged**
