### PR TITLE
NAM-174 -- UI: Add more loading Icons for when Data is loading to improve usability

### PR DESCRIPTION
**Pull request by jazperez**
Description: Loading buttons appear when courses, menu, and student profiles are loading. 

Installation: none 

Testing: Go through the application, open the menu, look at the courses and student profiles.  Loading buttons appear when courses, menu, and student profiles are loading.

### CODE REVIEW

**Review by maseca — CHANGES_REQUESTED** [review]
If I refresh the page, the loading spinners never go away.  Tie the spinner logic to whether or not the state items are null, because now the state persists after refresh.  If the data is retrieved once, we shouldn't see the spinners ever again.

**Review by chippingcolt — CHANGES_REQUESTED** [review]
Hey, can you delete the comment code, and when I was testing the student profile with max the spinner doesn't appear when loading new students.

**Review by maseca — APPROVED** [review]
:oncoming_police_car:

**Review by liadGolan — APPROVED** [review]
:+1:

**Pull request merged**
