### PR TITLE
NAM-140 -- CSS REFACTOR

### PR DESCRIPTION
**Pull request by chippingcolt**
Description:  I have added the ability of themes and refactored much of the css to be re-usable and fixed some of the structure within nameface.  There still needs to be refactoring, but if this ticket is impeding other tasks, this current state should work and create enough of re-usable css to continue all tickets for this week.  I will be continuing refactoring.

Testing:  PLEASE make sure that all pages work properly and if some styling is off from past tickets let me know.  There is commented code because it is still being finished.  As far as the profile page, since it is being completely restyled I took the style out of it and just left the structure (functionality is there).

### CODE REVIEW

**Review by maseca — CHANGES_REQUESTED** [review]
.

**Review by maseca — APPROVED** [review]

**Review by liadGolan — DISMISSED** [review]
Names on list items are not uniform
Flashcards are two different sizes based on their side that is showing
Gallery Cards are not uniform in size

Also could you delete your likeness photos for Alex and Gabe? those changed would override the images I put for everyone

**Review by liadGolan — CHANGES_REQUESTED** [review]
People with longer names have longer gallery cards on mobile view

People with longer names have uneven name placement on mobile view for list items

**Review by liadGolan — DISMISSED** [review]
:+1:  amazing

**Pull request merged**
