### PR TITLE
NAM-193 -- UI: Unified Back Button

### PR DESCRIPTION
**Pull request by maseca**
# Description
> This is a back button that lets you go from
> 1. the student list/grid to the course list 
> 2. from the student profile to where you previously were
***
# Testing
* Check that button follows description logic

### CODE REVIEW

**Review by jazperez — APPROVED** [review]
👍🏼

**Review by liadGolan — CHANGES_REQUESTED** [review]
Login page is broken, cant login. There is no submit button or anything

**Review by liadGolan — CHANGES_REQUESTED** [review]
We are no longer doing scoped styling, all styling should be within the sass folder. If you have any question on how the styling should be organized, ask Tim (he gets in at 12)

**Review by liadGolan — APPROVED** [review]
:+1:

**Pull request merged**
