### PR TITLE
NAM-373 -- UI: Add ability to set default photo through profile modal in profile view

### PR DESCRIPTION
**Pull request by alecnicolas**
# Description
Profile carousel implemented.
  
# Testing
Try setting a default photo for your student.

### CODE REVIEW

**Review by jazperez — CHANGES_REQUESTED** [review]
There's still a 500 error occurring 😢

**Review by liadGolan — CHANGES_REQUESTED** [review]
500 error still occurs.
I can no longer swipe between the two images I have to press the carousel buttons.
Clicking set default changes the bottom of the carousel for some reason
Also there's a console log still here somewhere

**Review by liadGolan — APPROVED** [review]
:1st_place_medal:

**Review by jazperez — APPROVED** [review]
yay! muy bueno!

**Pull request merged**
