### PR TITLE
HOTFIX-6-22-2018-titleNotPopulatedOnBookmark

### PR DESCRIPTION
**Pull request by liadGolan**
# Description
When saving a bookmark, a title does not appear automatically
  
# Testing
Ensure that the tag for a title is present (we will be unable to ensure it works until it is in the demo environment)

### CODE REVIEW

**Review by Tiffufu — APPROVED** [review]
Approving so we can test on demo

**Review by luisjg — CHANGES_REQUESTED** [review]
See comments.

**Review by luisjg — APPROVED** [review]
👍

**Review by alecnicolas — COMMENTED** [review]
lol

**Pull request merged**
