### PR TITLE
NAM-354 -- UI: Organize the SCSS and conform to BEM

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Refactored CSS to BEM standards; refactored login page from 2 modules to 1 single responsive module.
  
# Testing
1. Ensure all functionality within login page works.
2. Test login page responsiveness and feature set.
3. Check all routes/pages to see if all CSS attributes are applied.
4. Ensure that BEM is applied to all CSS tags within our new CSS file structure.
5. Ensure login input scrolls when the users keyboard covers the screen.

### CODE REVIEW

**Review by chippingcolt — CHANGES_REQUESTED** [review]
I haven't got a chance to review ALL of the BEM changes, but I noticed right off the bat that you are adding axios calls to mutations which undos your previous task

**Review by chippingcolt — DISMISSED** [review]
You also added console log method, I think what happened was you accepted your changes over dev.  My suggestion is to go back to a previous commit and accept incoming changes from dev and fix merge conflicts.

**Review by alecnicolas — COMMENTED** [review]
- So the BEM changes make sense and look good. I think you missed a few so just go through one more time and make sure every class is using the BEM standard when applicable.

- Also, conforming to BEM was just half of this task. The other half of this task is to organize the SCSS files however you see fit. 
- Whether this be organizing the files into views, components, etc is up to you. "Helpers" and "Layout" are very broad file names and it can be difficult to find a specific class.

**Review by chippingcolt — DISMISSED** [review]
Sorry one last small change on your support.blade.php file you undo the back button fix so the it goes to the courselist page rather than the previous page.  Just change it to "onclick="window.history.back()"

**Review by alecnicolas — APPROVED** [review]
I love it 🎉

**Review by chippingcolt — APPROVED** [review]
Great!!

**Pull request merged**
