### PR TITLE
NAM-404 -- UI: In course view, make previous, current, & next buttons equal width.

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Made buttons equal width and added a check to see what course term the user is on for the button color.
  
# Testing
1. Make sure the button width is equal to each other.
2. Ensure the buttons are scale-able at different view-ports.
3. Make sure the correct color theme is applied to each button.
4. See if the color only applies to the correct term selected

### CODE REVIEW

**Review by liadGolan — DISMISSED** [review]
The unselected buttons are hard to see as buttons on all of the color themes.

Also, this was not in the task description, but there needs to be a small descriptor that explains to the user that they are choosing between terms

**Review by liadGolan — APPROVED** [review]
:+1:

**Review by alecnicolas — DISMISSED** [review]
I don't think the term selector should disappear when loading a term

**Review by alecnicolas — APPROVED** [review]
💯

**Pull request merged**
