### PR TITLE
NAM-416 -- ENG and UI: Permission should not be asked every single time the user enters the application. We should remember when the user says yes once

### PR DESCRIPTION
**Pull request by jazperez**
# Description
Permission should not be asked every single time the user enters the application. We should remember when the user says yes once.
 
# Testing
Login in as Steve. 
Deny the permission when first log in. 
Modal should go away.
Go to a student profile and press the edit button.
Permission modal should appear again. 
This time accept it and the permission modal should go away and be replaced with the croppaModal. 
Log out and log in again as Steve. 
You should not be asked for your permission again. 

If you want to refresh the database, type 
php artisan migrate:fresh --seed 

# Installation
Before you start, do php artisan migrate:fresh --seed  in your docker container.

### CODE REVIEW

**Review by liadGolan — CHANGES_REQUESTED** [review]
After saying yes, the modal pops up for a half second

**Review by liadGolan — CHANGES_REQUESTED** [review]
Please make the simple changes reflected in the comments

**Review by liadGolan — APPROVED** [review]
:canada: :philippines: :jp: :new_zealand:

**Review by BrianLinggadjaja — APPROVED** [review]
🔥 🔥 🔥    🚒

**Pull request merged**
