### PR TITLE
NAM-382 -- UI: Add NOMI logo to mobile login page

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Changed the layout of the mobile login page to be more future proof; made design of login page look more mobile.
  
# Testing
1. Ensure all the colors are contrasted well enough.
2. Ensure colors meet CSUN guidelines.
3. Make sure there is no page breaks where anything will clip out of place.
4. Make sure there is proper accessibility; i.e tab and no image alts.
5. Check to see if all the proper functionality works and works the same as the old login page.

### CODE REVIEW

**Review by jazperez — DISMISSED** [review]
Liad, Alec, Jazmin: Looks good, too red. Like the concept, but push content up a little higher please.

**Review by alecnicolas — DISMISSED** [review]
There are errors and the Login button isn't visible because of white text on a white background. Also,you might want to consult with Tiffany about the placement of the login content on the page.

**Review by liadGolan — DISMISSED** [review]
The Form looks like it still is a bit too low, and where did the title bar go?

**Review by liadGolan — APPROVED** [review]
:+1:

**Review by alecnicolas — APPROVED** [review]
good, just avoid using id selectors for css

**Pull request merged**
