### PR TITLE
NAM-124 -- UI: Fix menu bar

### PR DESCRIPTION
**Pull request by jazperez**
Description: The menu bar appears immediately when nameface.test/ loads. There are four buttons on the menu bar, the toggle grid/list components button, the toggle flashcard/gallerycard button, the shuffle button and the side bar button. 

Installation: none 

Testing: load nameface.test/ and press the buttons to test

### CODE REVIEW

**Review by chippingcolt — DISMISSED** [review]
Checked it out looks good!

**Review by galabastro — DISMISSED** [review]
There's still remnants of the other buttons that is leaving a lot of blank space at the top of the page in `studentMatrix.vue` in the `roster_components` folder. Additionally, there's two student matrices in the project. We're going to have to delete one of them, probably.

**Review by maseca — CHANGES_REQUESTED** [review]
Grid/List toggle button should reflect current view state.  The icon can be a list when the view is a grid or a list, similarly the icon can be a grid for either.  A quick fix might be to change the icon to indicate functionality rather than state, i.e., # <=> = (# is grid and = is list) rather than # or =

**Review by chippingcolt — CHANGES_REQUESTED** [review]
Sorry, I have to request changes because the icons are buttons without metaphor styling and thats why they may look a little weird.  Also on chrome, it looks like when in mobile view the menu bar gets super tiny.  Whenever you are free, I think we should swarm on this task to knock it out.

**Review by chippingcolt — DISMISSED** [review]

**Review by maseca — APPROVED** [review]
👍

**Review by chippingcolt — APPROVED** [review]
Need task to map out the button functionality, but otherwise good! looks great!

**Pull request merged**
