### PR TITLE
failingDataCall

### PR DESCRIPTION
**Pull request by liadGolan**
# Description
Updates the data call 
# Testing 
Make sure the application still works

### CODE REVIEW

**Review by Tiffufu — CHANGES_REQUESTED** [review]
When logging is as Steve, got error:

There was an error: count(): Parameter must be an array or an object that implements Countable
Spring 2017 Courses

**Review by alecnicolas — CHANGES_REQUESTED** [review]
💔

**Review by luisjg — CHANGES_REQUESTED** [review]
It broke.

**Review by luisjg — COMMENTED** [review]
See comments.

**Review by alecnicolas — APPROVED** [review]
🐓

**Review by luisjg — APPROVED** [review]
👍

**Pull request merged**
