### PR TITLE
NAM-549 -- FE: Profile Carousel is not swipeable, and can only be navigated by the dots at the bottom

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Removed pointer events on panel simulation for edit button.

# Testing
1. Visit any student profile.
2. Make sure you can swipe through student and faculty uploaded.

### CODE REVIEW

**Review by andrewMETALAB — APPROVED** [review]
good solve, Brian!

**Review by andrewMETALAB — CHANGES_REQUESTED** [review]
ahhh, so this makes the "camera button" not work!!!

**Review by liadGolan — APPROVED** [review]
👍

**Review by andrewMETALAB — APPROVED** [review]
I tested in multiple devices and can confirm that this works. 👍

**Pull request merged**
