### PR TITLE
NAM-173 -- ENG: Fix Image Uploads for students who do not have a folder

### PR DESCRIPTION
**Pull request by maseca**
# Description
> Students who do not have a folder cannot get a folder made anymore, which is a really big issue. Make sure that a student who does not have a likeness photo can get a likeness photo
***
# Installation
* update your .env
***
# Testing
* Upload pictures through the front-end

### CODE REVIEW

**Review by jazperez — DISMISSED** [review]
Added a likeness photo, saved it, moved on to profile, and the student still does not have a likeness photo. Saving button gives me a 500 error

**Review by liadGolan — CHANGES_REQUESTED** [review]
writing to a new image to one that already exists now causes a 500 error

**Review by liadGolan — APPROVED** [review]
:100:

**Review by chippingcolt — APPROVED** [review]
COOL

**Pull request merged**
