### PR TITLE
NAM-384 -- BUG: Students tab doesn't highlight & become clickable even after selecting class

### PR DESCRIPTION
**Pull request by alecnicolas**
# Description
Fixes bug due to missing id in v-else element.
  
# Testing
Select a course from the courses page and the students tab should highlight, while the courses tab highlight is removed.

### CODE REVIEW

**Review by jazperez — CHANGES_REQUESTED** [review]
the students icon does not highlight when a class was selected

**Review by BrianLinggadjaja — APPROVED** [review]
👍

**Review by Tiffufu — APPROVED** [review]
It works!! 👍

**Review by jazperez — APPROVED** [review]
👍🏼

**Pull request merged**
