### PR TITLE
NAM-316 -- UI: Update Roster List View

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Set class container to full and added standard containers to studentmatrix.
  
# Testing
1. Ensure the list view extends the full screen width without going out of bounds.
2. Ensure all other views are properly set.
3. Ensure padding and margin fit the criteria of the task.

### CODE REVIEW

**Review by Tiffufu — CHANGES_REQUESTED** [review]
Brian, good start so far. I'm glad that you were able to get the panel to extend full width and I'm sure you learned a lot from it.

Some changes:
- Please be aware that list view currently shares the same class as gallery and flash cards, so it might be a good idea to create a new class (keeping BEM in mind) for the list view panels
- I see that you didn't quite match the single line border of the mockup, but I like your solution better. Please consider decreasing margin-bottom to 0.4rem to be a happy middle between the mockup and this new direction.

Thank you!

**Review by Tiffufu — APPROVED** [review]
👍 This is so legit.

**Review by liadGolan — CHANGES_REQUESTED** [review]
List items are not all the same size on some screen sizes
(207 x 638)

**Review by liadGolan — APPROVED** [review]
:chicken:

**Pull request merged**
