### PR TITLE
NAM-529 -- UI: Fix unable to click camera after swiping

### PR DESCRIPTION
**Pull request by chippingcolt**
# Description
Fixed issue with sliding and unresponsive camera button
  
# Testing
slide and click camera

# Installation

### CODE REVIEW

**Review by liadGolan — DISMISSED** [review]
Please do not delete the .env.example

**Review by BrianLinggadjaja — COMMENTED** [review]
The removal was unnessicary ^

**Review by liadGolan — APPROVED** [review]
:+1:

**Review by andrewMETALAB — APPROVED** [review]
it works!

**Pull request merged**
