### PR TITLE
NAM-269 -- UI: Fix email formatting in student page to fit on one line

### PR DESCRIPTION
**Pull request by liadGolan**
# Description
Updates the Email to be displayed in a modal
# Test
Check the student profile to ensure the email is more aesthetically pleasing

### CODE REVIEW

**Review by alecnicolas — COMMENTED** [review]
All good, just add padding on top of the email button 👅

**Review by alecnicolas — COMMENTED** [review]
I think the padding between the Show Email button and the Save Notes button should be larger than the padding between the Saves Notes button and the Notes input field to separate two different functions.

**Review by alecnicolas — APPROVED** [review]
🍑

**Review by Tiffufu — APPROVED** [review]
Modal works great!

**Pull request merged**
