### PR TITLE
NAM-499 -- UI: Some of the buttons on desktop do not behave like links on mouse hover.

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Added focus & hover color on clickable events.
  
# Testing
1. Hover through all buttons on NOMI.
2. Ensure an outline appears on all clickable events.
3. Make sure the test the colors on all themes for consistency.

### CODE REVIEW

**Review by andrewMETALAB — DISMISSED** [review]
Per our conversation, lets just apply hover effects to buttons (instead of every clickable element on the site). 👍

**Review by andrewMETALAB — DISMISSED** [review]
Great work. Just gonna request a couple minor additions: 

(1) on the ".roster-sorting" elements (the filter buttons), please add cursor: pointer to the hover state!
(2) same for the modal buttons (camera and check-mark icons)
(3) same for the flash card items

**Review by andrewMETALAB — APPROVED** [review]
Great work 👍

**Review by liadGolan — APPROVED** [review]
👍

**Pull request merged**
