### PR TITLE
NAM-528--UI: Caching Issue 

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Fixed the caching issue of images and added functionality to update image on upload.
  
# Testing
### NAM-528 
1. Visit the gallery page; click the upload button and upload and image.
2. Ensure the image is being updated both in the modal and in (student list, gallery card, and flash cards).
3. Visit any student profile page and ensure the image is updated.
4. Click the edit button on a student profile and upload a new image, ensure the image is updated in the student profile.
5. Repeat step 2.

### NAM-536
1. Clicking on Tony's profile should not result in an error.

#### If all of your testing (and more) passes please also move NAM-536 as this was done in this branch.

# Installation
1. Make sure your secret key in your .env is updated; and without ***?secret=*** attached to the key.

### CODE REVIEW

**Review by luisjg — CHANGES_REQUESTED** [review]
See comments

**Review by luisjg — DISMISSED** [review]

**Review by liadGolan — DISMISSED** [review]
I uploaded a photo on gallery and it did not update on profile

When I tried to refresh all the photos went away into the not found placeholder

**Review by liadGolan — APPROVED** [review]
:+1:

**Review by andrewMETALAB — DISMISSED** [review]
Brian, everything is working PERFECTLY between photo-gallery and profile-page. (Meaning, if I update an image using one of those components, the change is reflected in the other component). However... the flash-card and student-list components still display the old version of the image. We need to apply the technique used on photo-gallery and profile-page to flash-card and student-list. (I am open to you doing this in a separate branch if you feel that would be better).

**Review by andrewMETALAB — APPROVED** [review]
Great work Brian. This was a very difficult task and you KILLED it! Hope you learned some things along the way! 👍 👍 👍

**Pull request merged**
